language: python

sudo: false
env:
  matrix:
    - DOCS="true"
    - TESTS="true"
  global:
  - secure: "bAlhfcSJB7M790tVu1qOSaWUpoTfpmfesmDbOyQeniHsqow6jCjkkKxvEe5uDoeb1sCEyxiTA6/qO+Oc06/Ny1ODfah5LOFAfBw7Yr5O/ewUHYBuEuaTCj0kCQPQtJ348JGrLTZK3eiIRDYwXCplMCogQ/FpHgPKlVYFPkJ1v1ttPH4ZaIE6hT68X/43MHZ6QBvIK9PHd+tUN9/YPjmuAGnmaEbf0X2O8vz5xCVey+wpHzviy9nAtmHaDuiQYfx6HolNhAG0dLxOY/DwzbjGwljzTkqR1SUo3ex4Q7itt2Xpto+S1LvPdWl91nX9jX6uCi7rOD0Qko8omU5bW1KNupj45yFpCgrWDR4hw/BYGz6vvNkT6ZSiRRt0IYS+ZNA4JTwL9A8iu19z8bJS1i1lreM8QsVZR9IRXvyyz/EUco+0RRr9h3UpeSFCnDesMGTzjoDkijUaW0LlfRpr4B3fqgyK5EvOucZrsWLPc2hIdv2BjwSw2/4SmbX5qcufnTvQefxQ2+AbPwftxYAdQX2WCLpa/a/hLZqgGyabnWiXmJUUxiiiJrr1K5h7FPAMUIx4cDsBBVEYaNbVmOUJ3pyucycVIhf58fe7DGxSvP1O830qe/comDsnnfHYQVfE9IuFVtt3jomnuimhz1KGGkrXI0eqGrQJppVEgzbzEDN1cFA="


install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge # For sphinxcontrib.autoprogram
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=3.5 requests cryptography sphinx pyflakes sphinxcontrib-autoprogram pytest sphinx-issues
  - source activate test-environment

script:
  - set -e
  - set -x
  - if [[ "${DOCS}" == "true" ]]; then
      cd docs;
      make html;
      cd ..;
      python -m doctr deploy --deploy-repo gforsyth/doctr_test_deploy --deploy-branch master;
    fi
  - if [[ "${TESTS}" == "true" ]]; then
      pyflakes doctr;
      py.test doctr;
    fi
